### ISSUE TITLE
[Demande] Scan fruggr et ajout certif

### ISSUE THREAD

**Issue by xavierdesnoyers** [digital4better/laplie#41]

**Comment by KuSh** [comment]
Le scan n'est pas possible aujourd'hui car non hébergé à la racine d'un domaine.
Fruggr ne prend (et c'est dommage) pas en charge ce type d'hébergement

**Comment by dlecan** [comment]
On peut lancer une l'analyse de répertoire avec le scanner dispo
@xavierdesnoyers C'est quoi l'URL du service numérique ? tu crées l'organisation fruggr ?

**Comment by KuSh** [comment]
> On peut lancer une l'analyse de répertoire avec le scanner dispo @xavierdesnoyers C'est quoi l'URL du service numérique ? tu crées l'organisation fruggr ?

Ce n'est pas pérenne, demande un effort à chaque analyse, je préfère qu'on ne le fasse pas tant que la fonctionnalité n'est pas réellement dispo dans fruggr (attention ce board est publique)
